---
title: "HR_Analytics_II"
author: "Tapas_Mohanty"
date: "24 February 2018"
output: html_document
---

```{r}
rm(list = ls());gc()
setwd('/home/tapas/HR_Analytics/')
library(dplyr)
library(data.table)
library(gridExtra)
library(ggplot2)
library(corrplot)
```


```{r}
hr <- read.csv('hr.csv',header = T)
hr$Employee.Count<- NULL
hr$Employee.ID <- NULL
setDT(hr)
Target <- data.frame(hr[ ,c(3)])
Target$Target <- Target$Attrition..Yes.No.
Target$Attrition..Yes.No. <- NULL
```


```{r}
cat_var <- names(hr)[which(sapply(hr, is.factor))]
cont_var <- names(hr)[which(sapply(hr, is.integer))]
hr_cat <- hr[,.SD, .SDcols = cat_var]
hr_cont <- hr[,.SD,.SDcols = cont_var]
hr_cat$Attrition..Yes.No. <- NULL
```


```{r}
#Plot Histogram for Caegorical data
plotHist <- function(data_in, i) {
  data <- data.frame(x=data_in[[i]])
  p <- ggplot(data=data, aes(x=factor(x))) + stat_count() + xlab(colnames(data_in)[i]) + theme_light() + 
    theme(axis.text.x = element_text(angle = 90, hjust =1))
  return (p)
}

doPlots <- function(data_in, fun, ii, ncol=3) {
  pp <- list()
  for (i in ii) {
    p <- fun(data_in=data_in, i=i)
    pp <- c(pp, list(p))
  }
  do.call("grid.arrange", c(pp, ncol=ncol))
}


hr_cont <- cbind(hr_cont,Target)

plotbox <- function(data_in, i){
  data <- data.frame(x=data_in[[i]], Target = data_in$Target)
  p <- ggplot(data= data) + geom_violin(aes( x = Target, y = x), stat = 'ydensity', size = 1,alpha = 1.0) +
    xlab(paste0((colnames(data_in)[i]))) + ylab(paste0(colnames(data_in$Target)))+ theme_light() 
  return(p)
  
}
```


```{r}
doPlots(hr_cat, fun = plotHist, ii = 1:4, ncol = 2)
```


```{r}
doPlots(hr_cat, fun = plotHist, ii = 5:8, ncol = 2)
```


```{r}
doPlots(hr_cat, fun = plotHist, ii = 9:12, ncol = 2)
```


```{r}
doPlots(hr_cat, fun = plotHist, ii = 13:15, ncol = 2)
```


```{r}
doPlots(hr_cont, fun = plotbox, ii = 1:4, ncol = 2)
```


```{r}
doPlots(hr_cont, fun = plotbox, ii = 5:8, ncol = 2)
```


```{r}
doPlots(hr_cont, fun = plotbox, ii = 9:12, ncol = 2)
```


```{r}
doPlots(hr_cont, fun = plotbox, ii = 13:17, ncol = 2)
```


```{r}

hr_cat_int <- hr[,(cat_var) := lapply(.SD, as.integer), .SDcols = cat_var]
hr_cat_int$Attrition..Yes.No. <-NULL
hr_cat_int$Standard.Hours <- NULL
hr_cat_int$Over.18 <- NULL
mydata <- hr_cat_int
head(mydata) 
cormat <- round(cor(mydata),2)
corrplot(cormat,method = 'pie')


```



